# Using node as a base image
FROM node:16

# Define the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Install Hardhat locally in the container
RUN npm install --save-dev hardhat

# Make the shell script executable
RUN chmod +x start.sh

# Expose the necessary port
EXPOSE 8545

# Run the shell script when the container starts
ENTRYPOINT ["./start.sh"]
